apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-eks
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/parag07jadhav/aws-webapp-infras.git'
    targetRevision: main
    path: k8s/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
